version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-banco
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"